services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "2000:2000"
    depends_on:
      - detective-club
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  detective-club:
    container_name: detective-club
    build:
      context: ./detective-club
    expose:
      - "4000"
